#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Pre-clear any globals to ensure the correct settings are applied.
###################################################################
unset XCPEDIR RPATH FSLDIR ANTSPATH AFNI_PATH C3D_PATH NUMOUT

###################################################################
# XCPEDIR stores a path to the top-level directory containing all
# of the ingredients necessary to configure and execute functional
# connectivity pipelines using the XCP Engine.
export XCPEDIR=/projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine
###################################################################

###################################################################
# RPATH stores a path to the local installation of R. Dependencies
# may include:
#  * ANTsR
#  * pracma
#  * signal
#  * optparse
export RPATH=/packages/R/3.5.1/bin/R
###################################################################

###################################################################
# FSLDIR stores a path to the local installation of FSL.
export FSLDIR=/packages/fsl/5.0.10/install
###################################################################

###################################################################
# ANTSPATH stores a path to the local installation of ANTs.
export ANTSPATH=/packages/ants/2.1.0/bin
###################################################################

###################################################################
# AFNI_PATH stores a path to the local installation of AFNI.
export AFNI_PATH=/packages/afni/18.2.04/
###################################################################

###################################################################
# C3D_PATH stores a path to the local installation of C3D.
export C3D_PATH=/projects/tau/packages/c3d/1.0.0/bin/c3d
###################################################################

###################################################################
# JQ_PATH stores a path to the local installation of JQ.
export JQ_PATH=/projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine/thirdparty/jq/jq-linux64
###################################################################

###################################################################
# Outputs of modules may be prepended with an integer indicating
# their context in the pipeline. Set NUMOUT to 1 to enable this.
export NUMOUT=0
###################################################################

